Learn/test0/base/urls.py
from django.urls import path
from . import views

app_name = "base"

urlpatterns = [
    path("", views.index, name="index"),
]

Learn/test0/recipe/urls.py
from django.urls import path
from . import views

app_name = "recipe"

urlpatterns = [
    path("", views.index, name="index"),
    
    path("view/<int:pk>", views.detail, name="detail"),
    path("update/<int:pk>", views.update_recipe, name="update_recipe"),
    path("delete/<int:pk>", views.delete_recipe, name="delete_recipe"),
    
    
    path("login/", views.login, name="login"),
    path("logout/", views.logoutt, name="logout"),
    path("signup/", views.signup, name="signup"),
    
]

Learn/test0/test0/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    
    #UserAuth
    path("user/", include("userauth.urls")),
    
    #My apps Urls
    path("", include("portfolio.urls")),
    path("base/", include("base.urls")),
    path("urlshort/", include("urlshort.urls")),
    path("recipe/", include("recipe.urls")),
    path("cg/", include("cgpa.urls")),
]



urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Learn/test0/recipe/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Recipe(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    title = models.CharField(max_length=200, default="Chicken Curry")
    description = models.TextField(default="This is a chicken curry recipe.")
    
    
    day = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.title} - {self.user.username}"
    
    class Meta:
        verbose_name = "Recipe"
        verbose_name_plural = "Recipess"

Learn/test0/recipe/views.py
from django.shortcuts import render, redirect
from .models import Recipe
from django.contrib.auth import login as auth_login, authenticate, logout
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    user = request.user
    if request.method == "POST":
        data = request.POST
        title = data.get("title")
        description = data.get("description")
        recipe = Recipe.objects.create(user=user, title=title, description=description)
        recipe.save()
        return redirect('recipe:index')
    
    recipes = Recipe.objects.order_by("-day")
    
    context = {
        "recipes":recipes,
    }
    return render(request, "recipe/index.html", context)

def detail(request, pk):
    
    recipe = Recipe.objects.get(id=pk)
    
    context = {
        "recipe":recipe,
    }
    return render(request, "recipe/detail.html", context)



@login_required(login_url="recipe:login")
def delete_recipe(request, pk):
    recipe = Recipe.objects.get(id=pk)
    recipe.delete()
    return redirect("recipe:index")

@login_required(login_url="recipe:login")
def update_recipe(request, pk):
    
    recipe = Recipe.objects.get(id=pk)
    
    if request.method == "POST":
        title = request.POST.get('title')
        description = request.POST.get('description')
        
        recipe.title = title
        recipe.description = description
        
        recipe.save()
        return redirect("recipe:index")
    context = {
        "recipe":recipe,
    }
    return render(request, "recipe/update_recipe.html", context)

#Login Page For User
def login(request):
    if request.method == "POST":
        try:
            username = request.POST.get("username")
            password = request.POST.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                auth_login(request, user)
                return redirect("recipe:index")
            else:
                messages.error(request, "Invalid Username or Password")
                print("Invalid Username or Password")
                return render(request, "recipe/login.html")
        except Exception as e: 
            messages.error(request, "Invalid Username or Password")
            print("Exception: ", e)
            return render(request, "recipe/login.html")
    return render(request, "recipe/login.html")


def logoutt(request):
    logout(request)
    return redirect("recipe:login")

def signup(request):
    if request.method == "POST":
        try:
            username = request.POST.get('username')
            password = request.POST.get('password')
            user_obj = User.objects.filter(username=username)
            
            if user_obj.exists():
                messages.error(request, "Username is taken")
                return redirect("recipe:signup")
            user = User.objects.create(username=username) #Here using password=password dosent works because thats not clean data I guess. 
            user.set_password(password)
            
            user.save()
            messages.success(request, "User Created Successfully")
            
        except Exception as e:
            messages.error(request, "Smething Went Wrong")
    
    return render(request, "recipe/sign-up.html")

Learn/test0/recipe/templates/recipe/detail.html
{% extends "base/base.html" %}

{% block content %}
<h1>Recipe detail</h1>

<div class="container mt-5">
    <div class="row">
        <div class="col">
            <h1 class="text-center">{{ recipe.title }}</h1>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col text-center">
            <!-- <img src="#" alt="{{ recipe.title }}" class="img-fluid"> -->
             
             
            <a class="btn btn-primary" href="{% url 'recipe:update_recipe' recipe.pk %}" role="button">Update</a>
            <a class="btn btn-danger" href="{% url 'recipe:delete_recipe' recipe.pk %}" role="button">Delete</a>
        </div>

    </div>
  
    <div class="row mt-4">
        <div class="col">
            <h2>Instructions</h2>
            <ol>
               
                    <li>{{ recipe.description|linebreaks }}</li>
                
            </ol>
        </div>
    </div>
</div>
{% endblock %}

Learn/test0/recipe/templates/recipe/index.html
{% extends "base/base.html" %}

{% block content %}
<style>
    .ok{
        color: white;
        text-decoration: none;
      }
      .ok:hover{
        color: white;
        text-decoration: none;
      }
     
    </style>
    
    <div class="container-3 col-6">
        <br><br>
        <form method="POST" class="col-6 mx-auto card p-3 shadow-lg" inctype="multipart/form-data">
            {% csrf_token %}
            <h3 class="text-center">Create Recipe</h3>
            <hr>

            <div class="form-control">
                <label for="title">Title</label>
                <input type="text" class="form-control" id="title" name="title" required>
            </div>

            <div class="form-group">
                <label for="description">
                    <textarea name="description" id="description" rows="5" cols="35"></textarea>
                </label>
            </div>

            <button type="submit">Add Recipe</button>
        </form>

        <hr>

        <div class="class mt-5">
            
            <table class="table mt-6">
                <thead>
                    <tr>
                        <th scope="col">Sr No</th>
                        <th scope="col">Title</th>
                        <th scope="col">Description</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for recipe in recipes %}
                    <tr>
                        <th scope="row">{{forloop.counter}}</th>
                        <td>{{recipe.title}}</td>
                        <td>{{recipe.description}}</td>
                        <td>
                            <a class="btn btn-primary" href="{% url 'recipe:update_recipe' recipe.pk %}" role="button">Update</a>
                            <a class="btn btn-danger" href="{% url 'recipe:delete_recipe' recipe.pk %}" role="button">Delete</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
{% endblock %}

Learn/test0/recipe/templates/recipe/update_recipe.html
{% extends "base/base.html" %}

{% block content %}
<div class="container mt-5 col-5">
    <form method="POST" class="col-6 mx-auto card p-3 shadow-lg">
        {% csrf_token %}
        <h1 class="text-center">Update Recipe</h1>
    <div class="form-group">
        
        <label for="title">Title</label>
        <input type="text" class="form-control" id="title" name="title" value="{{ recipe.title }}" required>

    </div>
    <div class="form-group">
        <label for="description">Description</label>
        <input type="text" class="form-control" id="description" name="description" value="{{ recipe.description }}" required>
    </div>

    <br><br>
    <button type="submit">Update Data</button>
    
    </form>
</div>
{% endblock %}